/*
 * lakeFS API
 *
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: services@treeverse.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrepareGarbageCollectionReferencesRequest {
    /// Minimum physical-file age. The server fixes the inventory cutoff before starting reference preparation.
    #[serde(rename = "minimum_age_seconds", skip_serializing_if = "Option::is_none")]
    pub minimum_age_seconds: Option<i64>,
}

impl PrepareGarbageCollectionReferencesRequest {
    pub fn new() -> PrepareGarbageCollectionReferencesRequest {
        PrepareGarbageCollectionReferencesRequest {
            minimum_age_seconds: None,
        }
    }
}

