/*
 * lakeFS API
 *
 * lakeFS HTTP API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: services@treeverse.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrepareGarbageCollectionReferencesStatus {
    #[serde(rename = "task_id")]
    pub task_id: String,
    /// True when preparation has finished, successfully or with an error.
    #[serde(rename = "completed")]
    pub completed: bool,
    #[serde(rename = "update_time")]
    pub update_time: String,
    /// Number of catalog entries examined so far.
    #[serde(rename = "progress")]
    pub progress: i64,
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::GarbageCollectionReferencesResult>>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::Error>>,
}

impl PrepareGarbageCollectionReferencesStatus {
    pub fn new(task_id: String, completed: bool, update_time: String, progress: i64) -> PrepareGarbageCollectionReferencesStatus {
        PrepareGarbageCollectionReferencesStatus {
            task_id,
            completed,
            update_time,
            progress,
            result: None,
            error: None,
        }
    }
}

