# coding: utf-8

"""
    lakeFS API

    lakeFS HTTP API

    The version of the OpenAPI document: 1.0.0
    Contact: services@treeverse.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
try:
    from pydantic.v1 import BaseModel, Field, conint
except ImportError:
    from pydantic import BaseModel, Field, conint

class PrepareGarbageCollectionReferencesRequest(BaseModel):
    """
    PrepareGarbageCollectionReferencesRequest
    """
    minimum_age_seconds: Optional[conint(strict=True, ge=1)] = Field(86400, description="Minimum physical-file age. The server fixes the inventory cutoff before starting reference preparation.")
    __properties = ["minimum_age_seconds"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PrepareGarbageCollectionReferencesRequest:
        """Create an instance of PrepareGarbageCollectionReferencesRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PrepareGarbageCollectionReferencesRequest:
        """Create an instance of PrepareGarbageCollectionReferencesRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PrepareGarbageCollectionReferencesRequest.parse_obj(obj)

        _obj = PrepareGarbageCollectionReferencesRequest.parse_obj({
            "minimum_age_seconds": obj.get("minimum_age_seconds") if obj.get("minimum_age_seconds") is not None else 86400
        })
        return _obj


